language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install coverage pytest flake8 isort tqdm
  - pip install mypy==0.812 numpyro

script:
  - coverage run -m pytest
  - black --check ./
  - isort ./
  - mypy ./metadPy/ --ignore-missing-imports
  - flake8 ./

after_success:
  - bash <(curl -s https://codecov.io/bash)
